pipeline:
  steps:
    - parse_pdf
    - generate_plan
    - generate_dialogue
    - enhance_script
    - validate_script
    - generate_audio
    - merge_audio

options:
  use_enhancement: true
  use_validation: false
  run_in_stream_mode: false

defaults:
  output_directory: "sample_outputs/"
  language: "en"
