prompts:
  style: "conversational"
  tone: "friendly"
  complexity_level: "medium"  # e.g., 'simple', 'medium', 'advanced'
  insert_citations_note: true # if true, mentions "citations in the bio" in the introduction
  
  # These could be used to inject certain phrases or ensure key instructions are always included
  required_phrases:
    - "For more details, please see the citation in the bio."
    - "Manu"     # Ensure the host’s name is always used correctly
    - "Open AI"   # Ensure the guest’s name is always used correctly

  fallback_prompt: "If you're unsure, provide a concise explanation."

limits:
  max_sections: 10
  max_dialogue_exchanges: 40
