prompts:
  style: "conversational"
  tone: "friendly"
  complexity_level: "medium"
  insert_citations_note: true
  required_phrases:
    - "For more details, please see the citation in the bio."
    - "Manu"
    - "Open AI"
  fallback_prompt: "If you're unsure, provide a concise explanation."

limits:
  max_sections: 10
  max_dialogue_exchanges: 40
