host:
  name: "Manu" # The host speaker's name
  voice_id: "EXAMPLE_VOICE_ID_FOR_HOST" # The host's ElevenLabs voice ID

guest:
  name: "Open AI" # The guest speaker's name
  voice_id: "EXAMPLE_VOICE_ID_FOR_GUEST" # The guest's ElevenLabs voice ID
